#!/bin/bash
echo "Calendars available"
gcsms -c "/opt/user/config/gcsms/gcsms" ls -l
echo "------------------"
echo " "
read -r -p "CREATE A CALENDAR:" calendarname
/usr/local/bin/gcsms -c "/opt/user/config/gcsms/gcsms" create $calendarname
/usr/local/bin/gcsms -c "/opt/user/config/gcsms/gcsms" unmute $calendarname
/usr/local/bin/gcsms -c "/opt/user/config/gcsms/gcsms" send $calendarname "This is a test" 
