#!/bin/bash
echo "Calendars available"
gcsms ls -l
echo "------------------"
echo " "
read -r -p "CREATE A CALENDAR:" calendarname
/usr/local/bin/gcsms create $calendarname
/usr/local/bin/gcsms unmute $calendarname
/usr/local/bin/gcsms send "This is a test" $calendarname 
