#!/bin/bash

description "Install oxplot/GCSMS"
messagebox "https://github.com/oxplot/gcsms"
installer python-pip
pip install gcsms
mkdir /opt/user/config/gcsms
touch /opt/user/config/gcsms/gcsms

messagebox "Generating configuration /opt/user/config/gcsms/gcsms"
cat <<\EOF > /opt/user/config/gcsms/gcsms &&
[global]
    client_id = 
    client_secret = 
EOF

messagebox "Go to https://console.developers.google.com/project and go to Apis & Auth / Credentials"
read -r -p "CLIENT ID:" client_id
replaceLine "/opt/user/config/gcsms/gcsms" "client_id =" "client_id = $client_id" "\[global\]"
read -r -p "CLIENT SECRET:" client_secret
replaceLine "/opt/user/config/gcsms/gcsms" "client_secret =" "client_secret = $client_secret" "\[global\]"
gcsms -c "/opt/user/config/gcsms/gcsms" auth

description "Installation finished!"
messagebox "You need to create a calendar gcsmsAddCalendar"
