#!/bin/bash

description "Install oxplot/GCSMS"
messagebox "https://github.com/oxplot/gcsms"
installer python-pip
pip install gcsms
touch /root/.gcsms

messagebox "Generating configuration /root/.gcsms"
cat <<\EOF > /root/.gcsms &&
[global]
    client_id = 
    client_secret = 
EOF

messagebox "Go to https://cloud.google.com/console and go to Apis & Auth / Credentials"
read -r -p "CLIENT ID:" client_id
replaceLine "/root/.gcsms" "client_id =" "client_id = $client_id" "\[global\]"
read -r -p "CLIENT SECRET:" client_secret
replaceLine "/root/.gcsms" "client_secret =" "client_secret = $client_secret" "\[global\]"
gcsms auth

description "Installation finished!"
messagebox "You need to create a calendar gcsmsAddCalendar"
